version: "3.3"
services:
   flask_app:
      container_name: app_container
      build: .
      ports:
         - "5000:5000"
      env_file: 
         - .env
      depends_on: 
         - redis
      command: gunicorn -w 2 -b 0.0.0.0:5000 app:app --timeout 120
   redis:
      image: redis:alpine
      container_name: redis_container
      restart: always
      ports:
         - "6379:6379"
      env_file:
         - .env